### ISSUE TITLE
Custom text and compat

### ISSUE THREAD

**Issue by stevelacey** [seanmavley/DjangoHoldit#1]
Would be good if this was simply a drop in replacement for placehold.it – it'd be most of the way there if it supported custom text and the URL's were the same.

**Comment by seanmavley** [comment]
Hi. Custom text, I'll try to add that. About the "URLs were the same" part, please help me understand that part.

**Comment by stevelacey** [comment]
i.e. the url pattern was the same as plachold.it's

http://placehold.it/160x120/ff0000/0000ff&text=requested

**Comment by seanmavley** [comment]
Oh okay. I see. Those are nice features worth adding.

Since the color is already added, what's needed is just the text part, which shouldn't be hard to do, I think.

Thanks.

**Comment by stevelacey** [comment]
I don't get how the color works, it's definitely not the same as placehold.it – I want to provide hex colors for bg/text color

**Comment by seanmavley** [comment]
Current, color only works for the image generated, and only supports rgb. 

Specifying the color goes like:
http://i.khophi.co/500x500/as/172.153.16/

I planed adding the alpha part but couldn't wrapped my head around doing that yet. That was the reason for the choose or rgb instead of hex.

**Comment by stevelacey** [comment]
I ended up writing my own solution that mirrors http://placehold.it
https://github.com/stevelacey/django-placeholdit
